no-witness-labs/lucid-evolution

.changeset/happy-tigers-do.md, packages/provider/src/kupmios.ts
Fix protocol param names from Ogmios.
Fixes #93
=> Fix Ogmios protocol params

.changeset/gold-candles-appear.md, packages/provider/src/kupmios.ts
Update submitTx call on Kupmios provider to match Ogmios v6.x
=> Fix submitTx to Ogmios

.changeset/popular-seahorses-itch.md, packages/lucid/src/tx-builder/internal/CompleteTxBuilder.ts, packages/lucid/test/coinselection.test.ts, packages/lucid/test/specs/hello-params.ts, packages/lucid/test/specs/hello.ts, packages/lucid/test/specs/services.ts, packages/lucid/test/specs/stake.ts, packages/lucid/test/specs/tx-chaining.ts, packages/lucid/test/specs/utils.ts, packages/lucid/vitest.config.ts
This PR fixes situations where the Lovelace asset sent to the change address is insufficient, causing the transaction to fail. An example of this condition can be found below:
```typescript
{
txHash: '197f6f6ea48bc20b72315613814e5e551f50430e99cf397f6639f2a7c41cc13b',
outputIndex: 1,
assets: {
lovelace: 228825 ,
'1c05caed08ddd5c9f233f4cb497eeb6e5f685e8e7b842b08897d1dfe4d794d696e746564546f6b656e': 1n,
'501b8b9dce8d7c1247a14bb69d416c621267daa72ebd6c81942931924d794d696e746564546f6b656e': 1n,
eb8b660cf939281c277264389c4086e7c79baf78e08d0c48668420ab4d794d696e746564546f6b656e: 1n
},
address: 'addr_test1qrngfyc452vy4twdrepdjc50d4kvqutgt0hs9w6j2qhcdjfx0gpv7rsrjtxv97rplyz3ymyaqdwqa635zrcdena94ljs0xy950',
datumHash: undefined,
datum: undefined,
scriptRef: undefined
}
```
=> feat: Ensure change address receives minimum required ADA

packages/uplc/package.json
Reverts Anastasia-Labs/lucid-evolution#214
=> Revert "fix: remove sideEffects from package.json"

.changeset/modern-mugs-arrive.md, packages/lucid/src/tx-builder/internal/Pay.ts, packages/lucid/src/tx-builder/internal/TxUtils.ts, packages/lucid/test/emulator/emulator.test.ts, packages/lucid/test/emulator/service.ts, packages/lucid/test/txHash.test.ts
=> fix: datum inclusion for asHash kind in payToContract

docs/pages/documentation/deep-dives/smart-contract-interactions.mdx, docs/pages/index.mdx, docs/pages/install.mdx
Added a customized view for mobile devices. The primary platform is still the computer, but these changes ensure compatibility across standard smartphones, tablets, and computers. There are minor tradeoffs between mobile and computer dimensions to accommodate the `animateCode` function on all devices.
=> docs: update docs for mobile devices

.changeset/great-radios-listen.md, packages/lucid/src/tx-builder/TxBuilder.ts
=> feat: add signer by reward address

.changeset/fluffy-wolves-reflect.md, packages/lucid/src/index.ts, packages/lucid/src/lucid-evolution/LucidEvolution.ts
fix https://github.com/Anastasia-Labs/lucid-evolution/issues/262
=> fix: add missing types

README.md, docs/pages/documentation/core-concepts/choose-wallet.mdx, docs/pages/documentation/core-concepts/instantiate-evolution.mdx, docs/pages/documentation/deep-dives/make-payments.mdx, docs/pages/documentation/deep-dives/mint-assets.mdx, docs/pages/documentation/deep-dives/register-stake.mdx, docs/pages/documentation/deep-dives/smart-contract-interactions.mdx, docs/pages/index.mdx, docs/pages/install.mdx, docs/theme.config.jsx
new readme, fixed favIcon on browsers, refined docs for importing packages
=> docs: update

.changeset/quick-geese-suffer.md, packages/provider/src/blockfrost.ts, packages/provider/src/emulator.ts, packages/provider/src/kupmios.ts, packages/provider/src/maestro.ts
=> feat: support reference native script

packages/lucid/test/onchain-preprod.test.ts, packages/lucid/test/onchain-preview.test.ts, packages/lucid/test/specs/contracts/plutus.json, packages/lucid/test/specs/contracts/validators/simple_mint.ak, packages/lucid/test/specs/mint-burn.ts, packages/lucid/test/specs/multi-validators.ts, packages/lucid/test/specs/services.ts
=> test: same validator with multi purposes in a tx

packages/provider/src/kupmios.ts
The current Kupmios implementation does not have any retry capability when fetching UTxOs from an address. 
This PR adds a retry policy to both the getDatumEffect & getScriptEffect functions for Kupmios which allows the backend to cope with 503 errors caused when Kupo reaches its maximum number of connections to the database. 
By adding just a small delay with a maximum of 10 retries, this can reduce the likelihood of errors dramatically.
I have not added retries for other methods as in my experience, it is getting the datums and scripts form a wallet's UTxOs that inundate the Kupo instance with requests.
=> Add retries to getDatumEffect & getScriptEffect for Kupmios

README.md, docs/pages/index.mdx, docs/pages/information/contact.mdx, docs/pages/showcase.mdx, docs/theme.config.jsx
new projects using the library are displayed on both pages
=> docs(update): showcase, readme, theme

.changeset/young-monkeys-wink.md, packages/lucid/src/tx-builder/internal/CompleteTxBuilder.ts, packages/lucid/src/tx-sign-builder/TxSignBuilder.ts, packages/provider/src/emulator.ts
=> feat: support map redeemer

README.md, docs/pages/index.mdx, docs/pages/showcase.mdx
- new projects shown under showcase in docs
- updated readme in sync with showcase section
- added visual content for the library to the index page
=> updated readme & project showcase

.changeset/tidy-impalas-smile.md, packages/lucid/src/tx-builder/internal/CompleteTxBuilder.ts, packages/lucid/test/coinselection.test.ts, packages/lucid/test/emulator/emulator.test.ts, packages/lucid/test/emulator/service.ts
=> feat: add option to include tiny change to transaction fee

.changeset/nine-stingrays-chew.md, packages/lucid/src/tx-builder/TxBuilder.ts, packages/lucid/src/tx-builder/internal/Collect.ts, packages/lucid/src/tx-builder/internal/CompleteTxBuilder.ts, packages/lucid/src/tx-builder/internal/Governance.ts, packages/lucid/src/tx-builder/internal/Interval.ts, packages/lucid/src/tx-builder/internal/Mint.ts, packages/lucid/src/tx-builder/internal/Pay.ts, packages/lucid/src/tx-builder/internal/Pool.ts, packages/lucid/src/tx-builder/internal/Service.ts, packages/lucid/src/tx-builder/internal/Signer.ts, packages/lucid/src/tx-builder/internal/Stake.ts, packages/lucid/src/tx-builder/internal/TxUtils.ts, packages/lucid/test/emulator/emulator.test.ts, packages/lucid/test/emulator/service.ts, packages/lucid/test/onchain-preprod.test.ts, packages/lucid/test/onchain-preview.test.ts, packages/lucid/test/specs/compose.ts, packages/lucid/test/specs/datums.ts, packages/lucid/test/specs/hello-params.ts, packages/provider/src/emulator.ts
=> Fix compose

.changeset/late-emus-retire.md, .github/workflows/main.yml, .github/workflows/release.yml, packages/provider/src/internal/koios.ts, pnpm-lock.yaml
fix https://github.com/Anastasia-Labs/lucid-evolution/issues/430
=> fix: koios

.changeset/purple-otters-approve.md, packages/lucid/src/lucid-evolution/LucidEvolution.ts, packages/lucid/src/tx-builder/TxBuilder.ts, packages/lucid/src/tx-builder/internal/CompleteTxBuilder.ts, packages/lucid/test/onchain-preprod.test.ts, packages/lucid/test/specs/multi-validators.ts
=> fix: minimum fee used in collateral calc

README.md, docs/pages/documentation/core-concepts/choose-wallet.mdx, docs/pages/documentation/core-concepts/instantiate-evolution.mdx, docs/pages/documentation/deep-dives/conway-era.mdx, docs/pages/documentation/deep-dives/make-payments.mdx, docs/pages/documentation/deep-dives/mint-assets.mdx, docs/pages/documentation/deep-dives/smart-contract-interactions.mdx, docs/pages/showcase.mdx, docs/theme.config.jsx
dark mode forced, showcase / readme page project update, showcase page component update
=> docs(update): nextra tab component removed in favour of a vertical layout

docs/pages/documentation/core-concepts/instantiate-evolution.mdx, docs/pages/documentation/deep-dives/conway-era.mdx, docs/pages/documentation/deep-dives/make-payments.mdx, docs/pages/documentation/deep-dives/mint-assets.mdx, docs/pages/documentation/deep-dives/smart-contract-interactions.mdx, docs/theme.config.jsx
better headers, and easier visual hierarchy
=> docs(update): vertical display refined

.changeset/strong-pumas-learn.md, packages/provider/package.json, packages/provider/src/internal/HttpUtils.ts, packages/provider/src/internal/koios.ts, packages/provider/src/internal/kupo.ts, packages/provider/src/internal/ogmios.ts, packages/provider/src/koios.ts, packages/provider/src/kupmios.ts, packages/provider/test/koios.test.ts, packages/provider/tsconfig.json, pnpm-lock.yaml
fix https://github.com/Anastasia-Labs/lucid-evolution/issues/439
replace https://github.com/Anastasia-Labs/lucid-evolution/pull/438
=> feat: upgrade kupmios and koios

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.yml, README.md, docs/pages/documentation/core-concepts/instantiate-evolution.mdx, docs/pages/index.mdx
updates the statement section or Lucid Evolution landing page/readme, update .yml templates
=> docs(update): statement update, update templates

docs/pages/documentation/core-concepts/under-the-hood.mdx, docs/pages/documentation/deep-dives/emulator.mdx, docs/pages/documentation/deep-dives/make-payments.mdx, docs/pages/documentation/deep-dives/smart-contract-interactions.mdx, docs/pages/documentation/examples/_meta.json, docs/pages/documentation/examples/design-patterns.mdx, docs/pages/documentation/examples/emulated-testing-framework.mdx, docs/pages/documentation/examples/hello-world.mdx
content on protocol parameters, fee calculation, emulator, examples
=> docs(update) - protocol parameters, fee calculation, emulator, examples

.changeset/gorgeous-kings-ring.md, packages/core-types/src/types.ts, packages/lucid/src/tx-builder/internal/Governance.ts, packages/lucid/tsup.config.ts
attempt to fix drep issue instance, moving all the util function into the governance module
=> fix: attempt to fix drep issue instance

docs/pages/documentation/core-concepts/under-the-hood.mdx, docs/pages/documentation/deep-dives/make-payments.mdx, docs/pages/documentation/deep-dives/register-stake.mdx
=> revise docs content: CML, hashes, minADA

.changeset/grumpy-sheep-lick.md, examples/with-react-cra/README.md, packages/lucid/package.json, packages/lucid/src/tx-builder/internal/Governance.ts, packages/lucid/test/specs/governance.ts
=> feat: add drepId to credential util

pnpm-lock.yaml
=> fix: pnpm-lock

packages/lucid/test/specs/services.ts
=> re-enable blockfrost test provider

docs/pages/documentation/deep-dives/smart-contract-interactions.mdx
Updated content on DoubleCborEncoding, format fixes on `with-react-cra/readme` 
=> docs: applyDoubleCborEncoding, format readme react-cra

packages/lucid/test/emulator/emulator.test.ts, packages/lucid/test/emulator/executor/SignExecutor.ts
=> test(emulator): add verify-message test

packages/lucid/test/onchain-preprod.test.ts, packages/lucid/test/specs/compose.ts
=> fix: update tests

.changeset/funny-beers-join.md, docs/pages/documentation/deep-dives/mint-assets.mdx
Improve CIP-0068 Token Standard Code example
N/A
=> [docs] Improve CIP-0068 Token Standard Code example

docs/pages/documentation/deep-dives/mint-assets.mdx
=> docs: fix Callout formatting in mint-assets docs

.changeset/quiet-knives-end.md, packages/lucid/package.json, packages/lucid/src/tx-builder/internal/Governance.ts, packages/lucid/test/specs/governance.ts, packages/utils/package.json, packages/utils/src/credential.ts, pnpm-lock.yaml
=> fix: expose drepIdToCredential

docs/pages/documentation/deep-dives/governance.mdx, docs/pages/documentation/deep-dives/make-payments.mdx, docs/pages/documentation/deep-dives/mint-assets.mdx, docs/pages/documentation/deep-dives/smart-contract-interactions.mdx, docs/pages/documentation/examples/_meta.json
Refreshed content on deep dive series
=> Docs update

CONTRIBUTING.md, README.md, docs/pages/documentation/core-concepts/first-transaction.mdx, docs/pages/documentation/core-concepts/instantiate-evolution.mdx, docs/pages/documentation/core-concepts/wallet-management.mdx, docs/pages/documentation/deep-dives/emulator.mdx, docs/pages/documentation/deep-dives/governance.mdx, docs/pages/documentation/deep-dives/mint-burn-assets.mdx, docs/pages/documentation/deep-dives/pay-methods.mdx, docs/pages/documentation/deep-dives/register-stake.mdx, docs/pages/documentation/deep-dives/smart-contract-interactions.mdx, docs/pages/documentation/deep-dives/transaction-chaining.mdx, docs/pages/documentation/examples/_meta.json, docs/pages/index.mdx
Deeper dive into certain topics, and updated README / CONTRIBUTING pages.
=> docs update content

.changeset/ninety-seas-press.md, packages/lucid/src/tx-builder/internal/CompleteTxBuilder.ts, packages/lucid/src/tx-builder/internal/Read.ts, packages/lucid/test/onchain-preprod.test.ts, packages/lucid/test/specs/compose.ts, packages/lucid/test/specs/tx-chaining.ts
=> fix: duplicate reference inputs

packages/lucid/src/tx-builder/internal/CompleteTxBuilder.ts
=> fix: allow coin selection to include inputs with scriptRef

.github/workflows/release.yml
=> ci: remove pnpm version

packages/experimental/docgen.json, packages/experimental/docs/modules/Data.ts.md, packages/experimental/src/Data.ts
=> docs: add data docs

.changeset/strange-ties-work.md, code-style.md, packages/experimental/docs/modules/Data.ts.md, packages/experimental/src/Data.ts
=> docs: update categories

.changeset/silver-eagles-draw.md, packages/provider/src/blockfrost.ts, packages/provider/src/kupmios.ts
=> feat: update awaitTx function

.changeset/moody-taxis-remember.md, flake.lock, flake.nix, packages/experimental/docgen.json, packages/experimental/docs/modules/Address.ts.md, packages/experimental/docs/modules/Credential.ts.md, packages/experimental/docs/modules/Data.ts.md, packages/experimental/docs/modules/KeyHash.ts.md, packages/experimental/docs/modules/ScriptHash.ts.md, packages/experimental/package.json, packages/experimental/src/Address.ts, packages/experimental/src/Address_old.ts, packages/experimental/src/CBOR.ts, packages/experimental/src/Credential.ts, packages/experimental/src/Credential_old.ts, packages/experimental/src/KeyHash.ts, packages/experimental/src/KeyHash_old.ts, packages/experimental/src/Script.ts, packages/experimental/src/ScriptHash.ts, packages/experimental/src/ScriptHash_old.ts, packages/experimental/src/index.ts, packages/experimental/test/Address_benchmark.ts, packages/lucid/tsconfig.json, pnpm-lock.yaml, turbo.json
=> feat: add credential, keyhash, scripthash effects

.changeset/dirty-suits-train.md, code-style.md, packages/experimental/docs/modules/Address.ts.md, packages/experimental/docs/modules/Credential.ts.md, packages/experimental/docs/modules/Data.ts.md, packages/experimental/docs/modules/KeyHash.ts.md, packages/experimental/docs/modules/ScriptHash.ts.md, packages/experimental/src/Address.ts, packages/experimental/src/Credential.ts, packages/experimental/src/KeyHash.ts, packages/experimental/src/Positive.ts, packages/experimental/src/ScriptHash.ts, packages/experimental/src/SerdeImpl.ts, packages/experimental/src/index.ts, packages/experimental/test/Address.test.ts
=> feat: improve module struct

.changeset/weak-dingos-drive.md, packages/experimental/docgen.json, packages/experimental/docs/modules/TSchema.ts.md, packages/experimental/src/TSchema.ts
=> feat: add TSchema docs

packages/experimental/docs/modules/Data.ts.md, packages/experimental/docs/modules/TSchema.ts.md, packages/experimental/src/Data.ts, packages/experimental/src/TSchema.ts, packages/experimental/src/old/Script.ts, packages/experimental/test/Data.test.ts, packages/experimental/test/DataProp.test.ts, packages/experimental/test/TSchema.test.ts
=> refactor: rename-cbor-data-fn-names

.changeset/swift-ways-hug.md, packages/experimental/docs/modules/Data.ts.md, packages/experimental/src/Data.ts
=> feat: update data dependency; add missing fn

code-style.md
=> docs: update code style

code-style.md
=> docs: format

.changeset/flat-ducks-lay.md, packages/experimental/docs/modules/Data.ts.md, packages/experimental/docs/modules/KeyHash.ts.md, packages/experimental/src/KeyHash.ts
=> feat: add nominal type keyhash

packages/experimental/src/Address.ts, packages/experimental/src/AddressDetails.ts, packages/experimental/src/AddressTag.ts, packages/experimental/src/ByronAddress.ts, packages/experimental/src/Credential.ts, packages/experimental/src/Header.ts, packages/experimental/src/KeyHash.ts, packages/experimental/src/Network.ts, packages/experimental/src/Pointer.ts, packages/experimental/src/old/Address_old.ts, packages/experimental/src/old/Credential_old.ts, packages/experimental/src/old/Script.ts, packages/experimental/test/Address.test.ts, packages/experimental/test/Address_benchmark.ts, packages/experimental/test/KeyHash_benchmark.ts
=> build: fix build

packages/experimental/src/DatumHash.ts, packages/experimental/test/DatumHash.test.ts
Updating DatumHash to use Effect with basic unit tests.
=> Refactor: DatumHash with Effect

.changeset/puny-fans-clean.md, packages/experimental/src/Address.ts, packages/experimental/src/CardanoNode/Devnet.ts, packages/experimental/src/CardanoNode/DevnetDefault.ts, packages/experimental/src/KeyHash.ts, packages/experimental/src/index.ts
=> feat: update devnet files; update code struct

packages/experimental/src/TransactionMetadatumLabels.ts, packages/experimental/test/TransactionMetadatumLabels.test.ts
`TransactionMetadatumLabels` work in progress
This is a work-in-progress to gather feedback regarding the Effect module before creating unit tests.
=> TransactionMetadatumLabels initial version

docs/src/app/globals.css, docs/src/app/page.tsx
If the feature is substantial or introduces breaking changes without a discussion, its best to open an [issue](https://github.com/no-witness-labs/lucid-evolution/issues) first.
=> docs: update nextra colors

docs/src/app/globals.css
If the feature is substantial or introduces breaking changes without a discussion, its best to open an [issue](https://github.com/no-witness-labs/lucid-evolution/issues) first.
=> fix: minor tweaks

CONTRIBUTING.md, README.md, docs/src/app/layout.tsx, docs/src/app/page.tsx, docs/src/components/Footer.tsx
If the feature is substantial or introduces breaking changes without a discussion, its best to open an [issue](https://github.com/no-witness-labs/lucid-evolution/issues) first.
=> docs: update info links
